#!/bin/bash
ID=$(cat ~/.vipaccess | grep id | awk -F 'id ' '{print $2}')
(while true; do (for i in $(seq 0 3.5 100); do echo $i; sleep 1; done) | zenity --window-icon=~/.local/share/icons/VipAccess.png --ok-label=Copied --progress --title "VIP Access" --text="        $ID\n\n\n\n              <b>$(vipaccess | xclip -f -sel c)</b>\n\n" --time-remaining --auto-close --auto-kill; done) > nul ; xclip -sel c < /dev/null; killall VipAccess
